# Site settings
title: William Matthias
email: b.matthias@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  William Matthias - University of Texas - Austin
url: "http://wtmatthias.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
