## Basic Configuration

baseurl = "https://wtmatthias.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "William Matthias"
title = "William Matthias"

theme = "hugo-goa"


## Hugo Built-in Features
disqusShortname = "billymatthias" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## permanent links to blog posts
[permalinks]
post = "/:year/:month/:day/:slug/"

## Site Settings
[params]
author = "William Matthias"
intro = "PhD Student at UT-Austin"
description = "Data. Politics & Development. Sports."
authorimage = "profile.jpg"
dateformat = "Jan 2, 2006"


## Site Meta Settings
[params.meta]
description = "conveying info on (mostly) politics and sports using data through programming and visualizations"
keywords = "politics,sports,development,conflict,R,Python,baseketball,sixers"

## Social Accounts
[params.social]
github = "<wtmatthias>"
instagram = "<wtmatthias>"
linkedin = "<william-matthias-668b1471>"
twitter = "<wtmatthias>"
# facebook = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
email = "b.matthias@utexas.edu"

## Extras
[params.extra]
copyright = "© 2017. William Matthias. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true # use highlight.js
highlightjsstyle = "atelier-forest-light" #highlight.js style
mathjax = true # Add to "footer.html". Not part of orig 'goa' theme

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
